# 
# Vagrantfile:
# - server node with docker 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Ubuntu trusty 64 VirtualBox.
    config.vm.box = "ubuntu/trusty64"

    # shared folder
    config.vm.synced_folder "./shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # server node setup
    #
    config.vm.define "server" do |node|
        node.vm.hostname = "server"   
        
        node.vm.provider "virtualbox" do |v| 
            v.memory = 2024
            v.cpus = 2 
        end 
        
        node.vm.network "private_network", ip: "10.11.1.101", virtualbox__intnet: true

        # http://localhsot:8080/ for use http://10.11.1.101:3000
        node.vm.network "forwarded_port", guest: 3000, host: 8080, id: 'web', auto_correct: true
        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
        # bash provisioning
        node.vm.provision :shell, :inline => 'apt-get update'
        # install docker
        node.vm.provision :shell, :inline => 'sh /home/vagrant/shared/scripts/install-docker-trusty.sh'
        node.vm.provision :shell, inline: "echo  'Server node setup completed'"
    end

end
